spring:
  application:
    name: retirement-planner
  datasource:
    url: jdbc:postgresql://localhost:5432/retirement_planner
    username: leedongwon
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  share-url: https://retirement-planner.vercel.app
  national-pension:
    a-value: 319.35